import "../globals.css";
import { Toaster } from "@/components/ui/toaster"
import localFont from 'next/font/local'
import Header from "@/components/myCustom/Header";
import Footer from "@/components/myCustom/Footer";


const valky = localFont({
  src: [
    {
      path: '../../../public/fonts/ValkyRegular.ttf',
      weight: '400'
    }
  ],
  variable: '--font-valky',
})

const raleway = localFont({
  src: [
    {
      path: '../../../public/fonts/Raleway-Regular.ttf',
      weight: '400'
    },
  ],
  variable: '--font-raleway',
})  

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${valky.variable} ${raleway.variable} font-sans`}>
      <body>
      <Header />
        {children}
        <Footer/>
      <Toaster />
      </body>
    </html>
  );
}
